import React, { useEffect, useState } from 'react';
import { ProgressBar, ListGroup, Tabs, Tab, Table } from 'react-bootstrap';

const SetupProgress = ({ onStatus }) => {
  const [counts, setCounts] = useState({ departments:0, buildings:0, courses:0, professors:0, students:0 });
  const [people, setPeople] = useState({ professors: [], students: [] });

  useEffect(()=>{
    const load = async ()=>{
      try{
        const token = localStorage.getItem('accessToken');
        const headers = { 'Content-Type': 'application/json' };
        if (token) headers['Authorization'] = `Bearer ${token}`;
        const [deps, bds, cs, profs, users] = await Promise.all([
          fetch('/api/departments/'), fetch('/api/buildings/'), fetch('/api/courses/'), fetch('/api/professors/'), fetch('/api/admin/users/', { headers })
        ]);
        const res = {};
        if (deps.ok) res.departments = (await deps.json()).length;
        if (bds.ok) res.buildings = (await bds.json()).length;
        if (cs.ok) res.courses = (await cs.json()).length;
        if (profs.ok) {
          const pjson = await profs.json();
          const p = Array.isArray(pjson) ? pjson : (pjson.results || pjson);
          res.professors = Array.isArray(p) ? p.length : 0;
          setPeople(prev => ({ ...prev, professors: Array.isArray(p) ? p : [] }));
        }
        if (users.ok) {
          const ujson = await users.json();
          const all = ujson.users || [];
          const studs = all.filter(x => x.role === 'student' || (!x.role && !x.is_staff && !x.is_superuser));
          res.students = studs.length;
          setPeople(prev => ({ ...prev, students: studs }));
        }
        setCounts(res);
        if (onStatus) onStatus(res);
      }catch(e){ /* ignore */ }
    };
    load();
  }, [onStatus]);

  // Progress counts exclude timeslots (generated by algorithm). 3 core items + professors
  const totalItems = 4;
  const have = (counts.departments>0?1:0) + (counts.buildings>0?1:0) + (counts.courses>0?1:0) + (counts.professors>0?1:0);
  const pct = Math.round((have/totalItems)*100);

  return (
    <div>
      <h5>Setup Progress</h5>
      <ProgressBar now={pct} label={`${pct}%`} />
      <Tabs defaultActiveKey="summary" className="mt-2">
        <Tab eventKey="summary" title="Summary">
          <ListGroup className="mt-2">
            <ListGroup.Item>Departments: {counts.departments}</ListGroup.Item>
            <ListGroup.Item>Buildings: {counts.buildings}</ListGroup.Item>
            <ListGroup.Item>Courses: {counts.courses}</ListGroup.Item>
            
            <ListGroup.Item>Professors: {counts.professors}</ListGroup.Item>
            <ListGroup.Item>Students: {counts.students}</ListGroup.Item>
          </ListGroup>
        </Tab>
        <Tab eventKey="people" title="People">
          <h6 className="mt-2">Professors</h6>
          <Table size="sm" striped>
            <thead><tr><th>Name</th><th>Department</th><th>Sub-department</th></tr></thead>
            <tbody>
              {people.professors.map(p => (
                <tr key={p.id}><td>{p.name}</td><td>{p.department_name || p.department || ''}</td><td>{p.sub_department_name || p.sub_department || ''}</td></tr>
              ))}
            </tbody>
          </Table>

          <h6 className="mt-3">Students</h6>
          <Table size="sm" striped>
            <thead><tr><th>Username</th><th>Email</th><th>Department</th><th>Sub-department</th><th>Year</th><th>Block</th></tr></thead>
            <tbody>
              {people.students.map(s => (
                <tr key={s.id}><td>{s.username}</td><td>{s.email}</td><td>{s.department_name || ''}</td><td>{s.sub_department_name || ''}</td><td>{s.year || ''}</td><td>{s.block_code || ''}</td></tr>
              ))}
            </tbody>
          </Table>
        </Tab>
      </Tabs>
    </div>
  );
};

export default SetupProgress;
