import React, { useEffect, useState } from 'react';
import { ProgressBar, ListGroup, Tabs, Tab, Table } from 'react-bootstrap';
import { apiFetch } from '../apiClient';

const SetupProgress = ({ onStatus }) => {
  const [counts, setCounts] = useState({ departments:0, buildings:0, courses:0, professors:0, students:0 });
  const [people, setPeople] = useState({ professors: [], students: [] });

  useEffect(()=>{
    const load = async ()=>{
      try{
        const token = localStorage.getItem('accessToken');
        const headers = { 'Content-Type': 'application/json' };
        if (token) headers['Authorization'] = `Bearer ${token}`;
        // fetch curricula (replaces former course-offerings), plus core models
        const promises = [
          apiFetch('/api/departments/', { headers }), 
          apiFetch('/api/buildings/', { headers }), 
          apiFetch('/api/courses/', { headers }), 
          apiFetch('/api/curricula/', { headers }), 
          apiFetch('/api/professors/', { headers })
        ];
        
        // Only fetch admin users if authenticated
        if (token) {
          promises.push(apiFetch('/api/admin/users/', { headers }));
        } else {
          promises.push(Promise.resolve({ ok: false })); // placeholder for admin users
        }
        
        const [deps, bds, cs, curricula, profs, users] = await Promise.all(promises);
        console.log('SetupProgress responses:', { deps: deps.ok, bds: bds.ok, cs: cs.ok, curricula: curricula.ok, profs: profs.ok, users: users?.ok });
        const res = {};
        if (deps.ok) {
          const depsJson = await deps.json();
          console.log('deps response:', depsJson);
          res.departments = Array.isArray(depsJson) ? depsJson.length : (depsJson.results ? depsJson.results.length : 0);
        }
        if (bds.ok) {
          const bdsJson = await bds.json();
          console.log('buildings response:', bdsJson);
          res.buildings = Array.isArray(bdsJson) ? bdsJson.length : (bdsJson.results ? bdsJson.results.length : 0);
        }
        if (cs.ok) {
          const csJson = await cs.json();
          console.log('courses response:', csJson);
          res.courses = Array.isArray(csJson) ? csJson.length : (csJson.results ? csJson.results.length : 0);
        }
        // map curricula -> offerings for compatibility with existing screens
        if (curricula.ok) {
          const cj = await curricula.json();
          console.log('curricula response:', cj);
          const cl = Array.isArray(cj) ? cj : (cj.results || []);
          res.curricula = cl.length;
          res.offerings = cl.length; // keep `offerings` key for legacy checks
        }
        if (profs.ok) {
          const pjson = await profs.json();
          console.log('professors response:', pjson);
          const p = Array.isArray(pjson) ? pjson : (pjson.results || pjson);
          res.professors = Array.isArray(p) ? p.length : 0;
          setPeople(prev => ({ ...prev, professors: Array.isArray(p) ? p : [] }));
        }
        if (users && users.ok) {
          const ujson = await users.json();
          console.log('users response:', ujson);
          const all = ujson.users || [];
          const studs = all.filter(x => x.role === 'student' || (!x.role && !x.is_staff && !x.is_superuser));
          res.students = studs.length;
          setPeople(prev => ({ ...prev, students: studs }));
        }
        console.log('SetupProgress final counts:', res);
        setCounts(res);
        if (onStatus) onStatus(res);
      }catch(e){ console.error('SetupProgress error:', e); }
    };
    load();
  }, [onStatus]);

  // Progress counts exclude timeslots (generated by algorithm). 3 core items + professors
  const totalItems = 4;
  const have = (counts.departments>0?1:0) + (counts.buildings>0?1:0) + (counts.courses>0?1:0) + (counts.professors>0?1:0);
  const pct = Math.round((have/totalItems)*100);

  return (
    <div>
      <h5>Setup Progress</h5>
      <ProgressBar now={pct} label={`${pct}%`} />
      <Tabs defaultActiveKey="summary" className="mt-2">
        <Tab eventKey="summary" title="Summary">
          <ListGroup className="mt-2">
            <ListGroup.Item>Departments: {counts.departments}</ListGroup.Item>
            <ListGroup.Item>Buildings: {counts.buildings}</ListGroup.Item>
            <ListGroup.Item>Courses: {counts.courses}</ListGroup.Item>
            <ListGroup.Item>Curricula: {counts.curricula || counts.offerings || 0}</ListGroup.Item>
            
            <ListGroup.Item>Professors: {counts.professors}</ListGroup.Item>
            <ListGroup.Item>Students: {counts.students}</ListGroup.Item>
          </ListGroup>
        </Tab>
        <Tab eventKey="people" title="People">
          <h6 className="mt-2">Professors</h6>
          <Table size="sm" striped responsive>
            <thead><tr><th>Name</th><th>Department</th><th>Sub-dept</th></tr></thead>
            <tbody>
              {people.professors.map(p => (
                <tr key={p.id}><td style={{maxWidth:'150px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.name}</td><td style={{maxWidth:'150px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.department_name || p.department || ''}</td><td style={{maxWidth:'100px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.sub_department_name || p.sub_department || ''}</td></tr>
              ))}
            </tbody>
          </Table>

          <h6 className="mt-3">Students</h6>
          <Table size="sm" striped responsive>
            <thead><tr><th>Username</th><th>Email</th><th>Dept</th><th>Sub-dept</th><th>Year</th><th>Block</th></tr></thead>
            <tbody>
              {people.students.map(s => (
                <tr key={s.id}><td style={{maxWidth:'100px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{s.username}</td><td style={{maxWidth:'120px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',fontSize:'0.85rem'}}>{s.email}</td><td style={{maxWidth:'80px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{s.department_name || ''}</td><td style={{maxWidth:'80px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{s.sub_department_name || ''}</td><td style={{maxWidth:'50px',textAlign:'center'}}>{s.year || ''}</td><td style={{maxWidth:'60px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{s.block_code || ''}</td></tr>
              ))}
            </tbody>
          </Table>
        </Tab>
      </Tabs>
    </div>
  );
};

export default SetupProgress;
