# Generated by Django 4.2.11 on 2026-03-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_timeslot_unique_together_timeslot_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='base.timeslot'),
        ),
    ]
