# Generated by Django 4.2.11 on 2026-03-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_course_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
