# Generated by Django 5.2.6 on 2026-03-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_add_professor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearLevel',
        ),
    ]
