# Generated by Django 5.2.6 on 2026-03-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_yearlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='course_offering',
        ),
        migrations.DeleteModel(
            name='CourseOffering',
        ),
    ]
