# Generated by Django 5.2.6 on 2026-03-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_scheduleentry_course_offering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='availability',
        ),
    ]
