# Generated by Django 4.2.11 on 2026-03-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_professor_id_alter_room_id_alter_section_id_and_more'),
        ('base', '0014_remove_professor_availability'),
    ]

    operations = [
    ]
